version: '3.8'

services:
  db:
    image: gvenzl/oracle-xe:21-slim-faststart
    container_name: daily-dev-insight-db
    environment:
      ORACLE_PASSWORD: password
      APP_USER: dailydev
      APP_USER_PASSWORD: password
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  oracle_data:
