spring:
  application:
    name: daily-dev-insight
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: dailydev
    password: password
    driver-class-name: oracle.jdbc.OracleDriver
  sql:
    init:
      mode: always

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dailydevinsight.domain
  configuration:
    map-underscore-to-camel-case: true
